# Generated by Django 3.1.1 on 2020-09-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
