# Generated by Django 3.1.1 on 2020-09-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_analysis', models.TextField(blank=True)),
                ('accuracy', models.TextField(blank=True)),
                ('script', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
