# Generated by Django 3.1.1 on 2020-09-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200917_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnail'),
        ),
    ]
