# Generated by Django 3.1.1 on 2020-09-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='tag_set',
            new_name='tag',
        ),
    ]
