# Generated by Django 3.1.1 on 2020-10-07 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullCourseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True)),
                ('emotions', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='videos.emotion')),
                ('gaze', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='videos.gaze')),
                ('head', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='videos.headposition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('video_file', models.FileField(blank=True, upload_to='videos')),
                ('audio_file', models.FileField(blank=True, upload_to='audios')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fullcourses.fullcourseresult')),
                ('tag', models.ManyToManyField(blank=True, to='fullcourses.Tag')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True)),
                ('value', models.IntegerField(blank=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nouns', to='fullcourses.fullcourseresult')),
            ],
        ),
    ]
