# Generated by Django 3.1.1 on 2020-10-07 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fullcourses', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcourseresult',
            name='emotions',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='videos.emotion'),
        ),
        migrations.AddField(
            model_name='fullcourseresult',
            name='gaze',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='videos.gaze'),
        ),
        migrations.AddField(
            model_name='fullcourseresult',
            name='head',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='videos.headposition'),
        ),
        migrations.AddField(
            model_name='fullcourse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AddField(
            model_name='fullcourse',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fullcourses.fullcourseresult'),
        ),
        migrations.AddField(
            model_name='fullcourse',
            name='tag',
            field=models.ManyToManyField(blank=True, to='fullcourses.Tag'),
        ),
        migrations.AddField(
            model_name='fullcourse',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nouns', to='fullcourses.fullcourseresult'),
        ),
    ]
